Add story kind regex
storybooks/storyshots pull request #92
Opened 2017-03-28 00:32 UTC by olistic

This closes #91.

Thanks for considering the PR!

2017-04-08 11:20 UTC, thani-sh requested changes

2017-04-08 11:20 UTC, mnmtanish commented on src/index.js
> +          if (options.storyNameRegex && !story.name.match(options.storyNameRegex)) {
Also support `options.storyRegex` so we don't break any storybooks. It's okay to remove it from the Readme file.

2017-04-08 11:27 UTC, mnmtanish commented
Hi @olistic,

Awesome PR :) Can you make a small change to the code so it'll continue to work with `options.storyRegex` also. Maybe you can add the following line somewhere.

```js
options.storyNameRegex = options.storyNameRegex || options.storyRegex
```

2017-04-08 15:27 UTC, olistic commented
Thanks @mnmtanish, the change is done!

2017-04-08 17:36 UTC, thani-sh approved these changes

2017-04-15 18:21 UTC, shilman commented
Hey @olistic 

Thank you so much for this PR! We're moving over to a mono-repo, since that makes a lot of sense for a project like this.

We would ❤️ it if you could create a PR here: https://github.com/storybooks/storybook

It looks like the changes have already been approved, so just let me know when it's ready and I'll merge it on the monorepo right away. Thanks and sorry for the hassle!

2017-04-15 18:21 UTC, closed without merging